# Profile information
name: San Jose Strong
title: San Jose Strong
description: > # this means to ignore newlines until "baseurl:"
  a grassroots platform designed to reinvent San Jose for and by the community
permalink: ':title/'
baseurl: "/sjstrong" # the subpath of your site, e.g. /blog
url: "https://ctychen.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
twitter: SanJoseStrong1
instagram: sanjose_strong

# Contact form
email: sanjose4blacklives@gmail.com


# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
